version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./monitoring:/usr/share/nginx/html/monitoring:ro
    depends_on:
      - web1
      - web2
      - web3
    networks:
      - app-network

  web1:
    build: ./web1
    ports:
      - "8081:80"
    networks:
      - app-network

  web2:
    build: ./web2
    ports:
      - "8082:80"
    networks:
      - app-network

  web3:
    build: ./web3
    ports:
      - "8083:80"
    networks:
      - app-network

  monitoring:
    image: nginx:latest
    ports:
      - "8084:80"
    volumes:
      - ./monitoring:/usr/share/nginx/html
    networks:
      - app-network

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "8085:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  influxdb_data:
  grafana_data: 